general {
    no_fade_in = false
    grace = 0
    disable_loading = true
}

background {
    monitor =
    path = /home/guilherme/Pictures/Wallpapers/wallpaper3.png
    color = rgba(0, 0, 0, 1.0)
    blur_passes = 3
    blur_size = 8
    noise = 0.008
    contrast = 0.95
    brightness = 0.72
    vibrancy = 0.0
    vibrancy_darkness = 0.0
}

label {
    monitor =
    text = $TIME
    color = rgba(245, 245, 245, 1.0)
    font_size = 112
    font_family = Inter Display ExtraBold
    position = 0, 92
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +'%A, %d de %B')</span>"
    color = rgba(180, 180, 180, 0.95)
    font_size = 22
    font_family = JetBrains Mono
    position = 0, -8
    halign = center
    valign = center
}

label {
    monitor =
    text = Olá, $USER
    color = rgba(245, 245, 245, 0.96)
    font_size = 17
    font_family = JetBrains Mono
    position = 0, -78
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 340, 56

    outline_thickness = 2
    rounding = 16

    dots_size = 0.38
    dots_spacing = 0.22
    dots_center = true
    dots_rounding = -1

    outer_color = rgba(38, 38, 38, 0.96)
    inner_color = rgba(8, 8, 8, 0.92)
    font_color = rgba(245, 245, 245, 1.0)

    fade_on_empty = false
    placeholder_text = <span foreground="##a3a3a3"><i>Senha</i></span>

    hide_input = true

    check_color = rgba(245, 245, 245, 1.0)
    fail_color = rgba(245, 245, 245, 1.0)
    fail_text = <span foreground="##bdbdbd"><i>Senha incorreta ($ATTEMPTS)</i></span>

    position = 0, -145
    halign = center
    valign = center
    zindex = 10
}
